"""
K-means persona cluster assignment.

Features (all normalized 0–1):
  [diversity, stability, curiosity, rabbit_hole_norm, fragmentation, drift, commercial]

where rabbit_hole_norm = min(rabbit_hole_depth / 20, 1.0)

Centroids are stored in ml/data/cluster_centroids.json (generated by train_clusters.py).
If the trained file is not found, falls back to the seed centroids defined here —
which encode domain knowledge about each archetype and are already meaningful.
"""

import json
import os
from pathlib import Path
from typing import Dict, List

import numpy as np

# ---------------------------------------------------------------------------
# Seed centroids — domain-knowledge-derived initial positions.
# These are used as: (a) fallback if no trained file exists, and
# (b) the initialization for k-means in train_clusters.py.
#
# Feature order: [diversity, stability, curiosity, rabbit_hole_norm,
#                 fragmentation, drift, commercial]
# ---------------------------------------------------------------------------

SEED_CENTROIDS = {
    "deep_diver": {
        "centroid": [0.20, 0.85, 0.25, 0.88, 0.12, 0.18, 0.30],
        "name": "The Deep Diver",
        "description": "Hyper-focused. Goes deep on one topic before moving on.",
    },
    "butterfly": {
        "centroid": [0.85, 0.20, 0.80, 0.14, 0.88, 0.58, 0.28],
        "name": "The Butterfly",
        "description": "Attention hops between topics constantly. High diversity, low focus.",
    },
    "algorithms_darling": {
        "centroid": [0.25, 0.82, 0.28, 0.55, 0.18, 0.18, 0.55],
        "name": "The Algorithm's Darling",
        "description": "Consistent, predictable, commercially engaged. Easy to profile.",
    },
    "ghost": {
        "centroid": [0.88, 0.28, 0.72, 0.24, 0.68, 0.42, 0.08],
        "name": "The Ghost",
        "description": "All over the place. Low commercial signal. Hard to pin down.",
    },
    "scholar": {
        "centroid": [0.62, 0.52, 0.90, 0.45, 0.48, 0.28, 0.07],
        "name": "The Scholar",
        "description": "Constantly seeking new topics. Knowledge-driven, low commercial intent.",
    },
    "trend_chaser": {
        "centroid": [0.58, 0.38, 0.58, 0.35, 0.62, 0.84, 0.38],
        "name": "The Trend Chaser",
        "description": "Interests shift with the cultural moment. High algorithmic drift.",
    },
    "loyalist": {
        "centroid": [0.28, 0.90, 0.20, 0.52, 0.16, 0.08, 0.28],
        "name": "The Loyalist",
        "description": "Knows what they like and sticks to it. Stable, low-drift patterns.",
    },
    "consumer": {
        "centroid": [0.42, 0.58, 0.38, 0.46, 0.40, 0.38, 0.93],
        "name": "The Consumer",
        "description": "High commercial intensity. Purchase-intent content dominates the feed.",
    },
}

_CENTROID_FILE = Path(__file__).parent / "data" / "cluster_centroids.json"
_FEATURE_ORDER = [
    "diversity",
    "stability",
    "curiosity",
    "rabbit_hole_norm",
    "fragmentation",
    "drift",
    "commercial",
]


def _load_centroids() -> Dict:
    """Load trained centroids if available, otherwise use seed centroids."""
    if _CENTROID_FILE.exists():
        with open(_CENTROID_FILE) as f:
            return json.load(f)
    return SEED_CENTROIDS


def _feature_vector(
    diversity: float,
    stability: float,
    curiosity: float,
    rabbit_hole_depth: int,
    fragmentation: float,
    drift: float,
    commercial: float,
) -> np.ndarray:
    rabbit_hole_norm = min(rabbit_hole_depth / 20.0, 1.0)
    return np.array(
        [diversity, stability, curiosity, rabbit_hole_norm, fragmentation, drift, commercial],
        dtype=float,
    )


def assign_cluster(
    diversity: float,
    stability: float,
    curiosity: float,
    rabbit_hole_depth: int,
    fragmentation: float,
    drift: float,
    commercial: float,
) -> Dict:
    """
    Assign a user's behavioral profile to the nearest persona cluster.

    Returns:
        id          — cluster identifier (e.g. "deep_diver")
        name        — human-readable persona name
        description — one-line archetype description
        confidence  — 0–1 score; higher = closer to the centroid (less ambiguous)
        distances   — distance to every centroid (for debugging / secondary persona)
    """
    centroids = _load_centroids()
    user_vec = _feature_vector(
        diversity, stability, curiosity, rabbit_hole_depth, fragmentation, drift, commercial
    )

    distances: Dict[str, float] = {}
    for cluster_id, info in centroids.items():
        c = np.array(info["centroid"], dtype=float)
        distances[cluster_id] = float(np.linalg.norm(user_vec - c))

    sorted_clusters = sorted(distances.items(), key=lambda x: x[1])
    best_id, best_dist = sorted_clusters[0]
    second_id, second_dist = sorted_clusters[1] if len(sorted_clusters) > 1 else (None, None)

    # Confidence: how much closer the nearest centroid is vs. the second nearest
    if second_dist and second_dist > 0:
        raw_confidence = 1.0 - (best_dist / second_dist)
    else:
        raw_confidence = 1.0
    confidence = round(float(np.clip(raw_confidence, 0.0, 1.0)), 3)

    info = centroids[best_id]
    return {
        "id": best_id,
        "name": info["name"],
        "description": info["description"],
        "confidence": confidence,
        "distances": {k: round(v, 4) for k, v in distances.items()},
    }


def get_all_cluster_ids() -> List[str]:
    return list(_load_centroids().keys())
