"""
Fine-tune DistilBERT as a topic classifier.

Pipeline:
  1. Load labeled data from ml/data/training_data.jsonl
     (generated by build_training_data.py)
  2. Fine-tune distilbert-base-uncased for 8-way sequence classification.
  3. Save the model to ml/models/topic_classifier/.

Run after build_training_data.py:
    cd backend
    python -m ml.train_classifier

The saved model is automatically picked up by classifier.py, replacing
BART-MNLI for inference (10x faster, ~67 MB vs ~1.5 GB).

Requirements:
    pip install scikit-learn transformers torch datasets
"""

import json
import sys
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).parent.parent))

DATA_FILE = Path(__file__).parent / "data" / "training_data.jsonl"
MODEL_OUTPUT = Path(__file__).parent / "models" / "topic_classifier"

LABELS = [
    "technology",
    "fashion",
    "politics",
    "finance",
    "self improvement",
    "entertainment",
    "health",
    "travel",
]

LABEL2ID = {label: i for i, label in enumerate(LABELS)}
ID2LABEL = {i: label for i, label in enumerate(LABELS)}


def load_data(path: Path) -> tuple[list[str], list[int]]:
    texts, label_ids = [], []
    with open(path) as f:
        for line in f:
            record = json.loads(line.strip())
            texts.append(record["text"])
            label_ids.append(LABEL2ID[record["label"]])
    return texts, label_ids


def train() -> None:
    if not DATA_FILE.exists():
        print(f"Training data not found at {DATA_FILE}")
        print("Run `python -m ml.build_training_data` first.")
        sys.exit(1)

    try:
        from datasets import Dataset
        from sklearn.model_selection import train_test_split
        from transformers import (
            AutoModelForSequenceClassification,
            AutoTokenizer,
            Trainer,
            TrainingArguments,
        )
        import torch  # noqa: F401
    except ImportError as e:
        print(f"Missing dependency: {e}")
        print("Install with: pip install transformers torch datasets scikit-learn")
        sys.exit(1)

    print(f"Loading data from {DATA_FILE}…")
    texts, label_ids = load_data(DATA_FILE)
    print(f"  {len(texts)} labeled examples across {len(LABELS)} topics")

    if len(texts) < 20:
        print("Too few examples to train. Run build_training_data.py with a lower threshold.")
        sys.exit(1)

    # Train/val split (80/20)
    train_texts, val_texts, train_labels, val_labels = train_test_split(
        texts, label_ids, test_size=0.2, stratify=label_ids, random_state=42
    )

    model_name = "distilbert-base-uncased"
    print(f"\nLoading tokenizer and model ({model_name})…")
    tokenizer = AutoTokenizer.from_pretrained(model_name)
    model = AutoModelForSequenceClassification.from_pretrained(
        model_name,
        num_labels=len(LABELS),
        id2label=ID2LABEL,
        label2id=LABEL2ID,
    )

    def tokenize(batch):
        return tokenizer(batch["text"], truncation=True, padding="max_length", max_length=128)

    train_ds = Dataset.from_dict({"text": train_texts, "labels": train_labels}).map(
        tokenize, batched=True
    )
    val_ds = Dataset.from_dict({"text": val_texts, "labels": val_labels}).map(
        tokenize, batched=True
    )

    def compute_metrics(eval_pred):
        logits, labels = eval_pred
        preds = np.argmax(logits, axis=-1)
        accuracy = float((preds == labels).mean())
        return {"accuracy": accuracy}

    training_args = TrainingArguments(
        output_dir=str(MODEL_OUTPUT / "checkpoints"),
        num_train_epochs=5,
        per_device_train_batch_size=16,
        per_device_eval_batch_size=32,
        warmup_steps=20,
        weight_decay=0.01,
        logging_dir=str(MODEL_OUTPUT / "logs"),
        evaluation_strategy="epoch",
        save_strategy="best",
        load_best_model_at_end=True,
        metric_for_best_model="accuracy",
        report_to="none",
    )

    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=train_ds,
        eval_dataset=val_ds,
        compute_metrics=compute_metrics,
    )

    print("\nFine-tuning DistilBERT…")
    trainer.train()

    final_metrics = trainer.evaluate()
    print(f"\nValidation accuracy: {final_metrics['eval_accuracy']:.3f}")

    print(f"\nSaving fine-tuned model to {MODEL_OUTPUT}…")
    MODEL_OUTPUT.mkdir(parents=True, exist_ok=True)
    model.save_pretrained(MODEL_OUTPUT)
    tokenizer.save_pretrained(MODEL_OUTPUT)

    # Save label map alongside the model for easy inspection
    with open(MODEL_OUTPUT / "label_map.json", "w") as f:
        json.dump({"id2label": ID2LABEL, "label2id": LABEL2ID}, f, indent=2)

    print("Done. classifier.py will automatically pick up the fine-tuned model.")


if __name__ == "__main__":
    train()
