"""
Topic classifier.

Loading priority:
  1. Fine-tuned DistilBERT at ml/models/topic_classifier/ (fast, ~67 MB)
     → generated by: cd backend && python -m ml.train_classifier
  2. BART-large-MNLI zero-shot (slow, ~1.5 GB first run)
     → automatic fallback if the fine-tuned model is not found

Both expose the same interface: classify_text(text) -> Dict[label, score]
"""

from pathlib import Path
from typing import Dict

labels = [
    "technology",
    "fashion",
    "politics",
    "finance",
    "self improvement",
    "entertainment",
    "health",
    "travel",
]

_FINETUNED_PATH = Path(__file__).parent / "ml" / "models" / "topic_classifier"


def _load_finetuned():
    """Try to load the fine-tuned DistilBERT classifier. Returns pipe or None."""
    if not _FINETUNED_PATH.exists():
        return None
    try:
        from transformers import pipeline as hf_pipeline
        print(f"[classifier] Loading fine-tuned model from {_FINETUNED_PATH}")
        return hf_pipeline(
            "text-classification",
            model=str(_FINETUNED_PATH),
            tokenizer=str(_FINETUNED_PATH),
            top_k=None,
        )
    except Exception as e:
        print(f"[classifier] Fine-tuned model failed ({e}), falling back to BART-MNLI")
        return None


def _load_bart():
    from transformers import pipeline as hf_pipeline
    print("[classifier] Loading BART-large-MNLI (zero-shot fallback)…")
    return hf_pipeline("zero-shot-classification", model="facebook/bart-large-mnli")


_finetuned = _load_finetuned()
_bart = None if _finetuned else _load_bart()


def classify_text(text: str) -> Dict[str, float]:
    """Classify text into topic probabilities. Returns {label: score}."""
    if _finetuned is not None:
        results = _finetuned(text, truncation=True, max_length=128)
        if isinstance(results[0], list):
            results = results[0]
        return {r["label"]: round(float(r["score"]), 4) for r in results}

    result = _bart(text, labels)
    return dict(zip(result["labels"], result["scores"]))


def using_finetuned() -> bool:
    return _finetuned is not None
